[theme]
name = "dracula"
[theme.overrides]
alternating_tint_bg = "#282A36"

[icons]
name = "awesome"
[icons.overrides]
cpu = ""
memory = ""

# includes a menu on click to show gh notifications
[[block]]
block = "github"
format = "{total}"
on_click = "~/.config/i3/scripts/rofi-github.sh"

[[block]]
block = "pacman"
interval = 600
format = "{both}"
format_singular = "{both}"
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"
on_click = "yay -Qua | rofi -dmenu -p \"Updates\""

[[block]]
block = "cpu"

[[block]]
block = "memory"
format_mem = "{mem_used} "
format_swap = " (swap) {swap_used} "
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon}  {used}/{total} "
alert_absolute = true
unit = "GB"
alert = 800
warning = 600

#[[block]]
#block = "docker"
#interval = 2
#format = "{running}/{total}"

[[block]]
block = "external_ip"
format = "  {ip} "
interval = 3600

[[block]]
block = "backlight"
minimum = 5
maximum = 100
cycle = [100, 75, 50, 25, 9, 25, 50, 75, 100]
format = " {brightness} "

[[block]]
block = "battery"
interval = 10
format = " {percentage} "

[[block]]
block = "time"
interval = 5
format = " %a %d/%m - %R "
